"""Rule-based domain classification rules.

Rules are evaluated in order; the first match wins.
Structure: (category, rule_type, pattern)
  rule_type: "exact", "suffix", "contains", "regex"
"""
from __future__ import annotations

from typing import NamedTuple

from .categories import Category


class Rule(NamedTuple):
    category: Category
    rule_type: str  # exact | suffix | contains | regex
    pattern: str


# ---------------------------------------------------------------------------
# RULE TABLE — evaluated top-to-bottom, first match wins
# ---------------------------------------------------------------------------
RULES: list[Rule] = [
    # -----------------------------------------------------------------------
    # ADULT_CONTENT — checked first so it is never shadowed
    # -----------------------------------------------------------------------
    Rule(Category.ADULT_CONTENT, "suffix", "xvideos.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "xnxx.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "pornhub.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "xhamster.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "onlyfans.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "redtube.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "youporn.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "tube8.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "spankbang.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "rule34.xxx"),
    # Major adult tube / studio / cam sites: deterministic, instant, no AI
    # spend — and no silent miss while free-model pools are throttled.
    Rule(Category.ADULT_CONTENT, "suffix", "beeg.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "youjizz.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "pornhd.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "porn.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "drtuber.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "tnaflix.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "empflix.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "hclips.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "upornia.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "vporn.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "xxxbunker.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "slutload.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "pornerbros.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "pornotube.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "keezmovies.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "extremetube.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "eporner.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "faphouse.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "brazzers.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "realitykings.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "bangbros.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "chaturbate.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "livejasmin.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "stripchat.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "bongacams.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "camsoda.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "myfreecams.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "cam4.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "nhentai.net"),
    Rule(Category.ADULT_CONTENT, "suffix", "hanime.tv"),
    Rule(Category.ADULT_CONTENT, "suffix", "betway.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "bet365.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "draftkings.com"),
    Rule(Category.ADULT_CONTENT, "suffix", "pokerstars.com"),
    Rule(Category.ADULT_CONTENT, "contains", "casino"),
    Rule(Category.ADULT_CONTENT, "contains", "gambling"),
    Rule(Category.ADULT_CONTENT, "contains", "betting"),
    Rule(Category.ADULT_CONTENT, "contains", "poker"),

    # -----------------------------------------------------------------------
    # ADS_TRACKING — before social to avoid false SOCIAL matches on ad pixels
    # -----------------------------------------------------------------------
    Rule(Category.ADS_TRACKING, "suffix", "doubleclick.net"),
    Rule(Category.ADS_TRACKING, "suffix", "googlesyndication.com"),
    Rule(Category.ADS_TRACKING, "suffix", "googletagmanager.com"),
    Rule(Category.ADS_TRACKING, "suffix", "googletagservices.com"),
    Rule(Category.ADS_TRACKING, "suffix", "adnxs.com"),
    Rule(Category.ADS_TRACKING, "suffix", "advertising.com"),
    Rule(Category.ADS_TRACKING, "suffix", "adsystem.amazon.com"),
    Rule(Category.ADS_TRACKING, "suffix", "scorecardresearch.com"),
    Rule(Category.ADS_TRACKING, "suffix", "moatads.com"),
    Rule(Category.ADS_TRACKING, "suffix", "facebook-pixel.com"),
    Rule(Category.ADS_TRACKING, "suffix", "criteo.com"),
    Rule(Category.ADS_TRACKING, "suffix", "outbrain.com"),
    Rule(Category.ADS_TRACKING, "suffix", "taboola.com"),
    Rule(Category.ADS_TRACKING, "suffix", "hotjar.com"),
    Rule(Category.ADS_TRACKING, "suffix", "mixpanel.com"),
    Rule(Category.ADS_TRACKING, "suffix", "segment.io"),
    Rule(Category.ADS_TRACKING, "suffix", "segment.com"),
    Rule(Category.ADS_TRACKING, "suffix", "amplitude.com"),
    Rule(Category.ADS_TRACKING, "suffix", "heap.io"),
    Rule(Category.ADS_TRACKING, "suffix", "quantserve.com"),
    Rule(Category.ADS_TRACKING, "suffix", "openx.net"),
    Rule(Category.ADS_TRACKING, "suffix", "rubiconproject.com"),
    Rule(Category.ADS_TRACKING, "suffix", "pubmatic.com"),
    Rule(Category.ADS_TRACKING, "suffix", "appsflyer.com"),
    Rule(Category.ADS_TRACKING, "suffix", "adjust.com"),
    Rule(Category.ADS_TRACKING, "suffix", "branch.io"),
    Rule(Category.ADS_TRACKING, "suffix", "telemetry.api.swiftkey.com"),
    Rule(Category.ADS_TRACKING, "suffix", "telemetry.microsoft.com"),
    Rule(Category.ADS_TRACKING, "suffix", "data.microsoft.com"),
    Rule(Category.ADS_TRACKING, "suffix", "browser.events.data.msn.com"),
    Rule(Category.ADS_TRACKING, "suffix", "events.data.microsoft.com"),
    Rule(Category.ADS_TRACKING, "suffix", "settings-win.data.microsoft.com"),
    Rule(Category.ADS_TRACKING, "contains", "telemetry."),
    Rule(Category.ADS_TRACKING, "contains", "analytics."),
    Rule(Category.ADS_TRACKING, "contains", "tracker."),
    Rule(Category.ADS_TRACKING, "contains", "tracking."),
    Rule(Category.ADS_TRACKING, "contains", "pixel."),
    Rule(Category.ADS_TRACKING, "contains", "metrics."),
    Rule(Category.ADS_TRACKING, "suffix", "crashlytics.com"),
    Rule(Category.ADS_TRACKING, "suffix", "bugsnag.com"),
    Rule(Category.ADS_TRACKING, "suffix", "sentry.io"),

    # -----------------------------------------------------------------------
    # SOCIAL_MEDIA
    # -----------------------------------------------------------------------
    Rule(Category.SOCIAL_MEDIA, "suffix", "facebook.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "facebook.net"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "fbcdn.net"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "instagram.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "cdninstagram.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "whatsapp.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "whatsapp.net"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "twitter.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "x.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "t.co"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "twimg.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "tiktok.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "tiktokv.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "snaptik.app"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "snapchat.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "sc-cdn.net"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "linkedin.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "licdn.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "reddit.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "redd.it"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "redditmedia.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "redditstatic.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "pinterest.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "pinimg.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "tumblr.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "discord.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "discord.gg"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "discordapp.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "telegram.org"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "t.me"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "signal.org"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "line.me"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "viber.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "vk.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "twitch.tv"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "twitchapps.com"),
    Rule(Category.SOCIAL_MEDIA, "suffix", "mastodon.social"),

    # -----------------------------------------------------------------------
    # STREAMING_VIDEO
    # -----------------------------------------------------------------------
    Rule(Category.STREAMING_VIDEO, "suffix", "youtube.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "youtu.be"),
    Rule(Category.STREAMING_VIDEO, "suffix", "ytimg.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "googlevideo.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "yt3.ggpht.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "netflix.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "nflxvideo.net"),
    Rule(Category.STREAMING_VIDEO, "suffix", "nflximg.net"),
    Rule(Category.STREAMING_VIDEO, "suffix", "nflxext.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "disneyplus.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "hulu.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "primevideo.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "amazonvideo.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "spotify.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "spotifycdn.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "scdn.co"),
    Rule(Category.STREAMING_VIDEO, "suffix", "apple.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "itunes.apple.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "music.apple.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "mzstatic.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "tidal.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "soundcloud.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "deezer.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "vimeo.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "peacocktv.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "hbomax.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "max.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "paramountplus.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "crunchyroll.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "funimation.com"),
    Rule(Category.STREAMING_VIDEO, "suffix", "twitch.tv"),
    Rule(Category.STREAMING_VIDEO, "suffix", "dailymotion.com"),

    # -----------------------------------------------------------------------
    # GAMING
    # -----------------------------------------------------------------------
    Rule(Category.GAMING, "suffix", "steampowered.com"),
    Rule(Category.GAMING, "suffix", "steamcommunity.com"),
    Rule(Category.GAMING, "suffix", "steam-chat.com"),
    Rule(Category.GAMING, "suffix", "akamaihd.net"),
    Rule(Category.GAMING, "suffix", "epicgames.com"),
    Rule(Category.GAMING, "suffix", "unrealengine.com"),
    Rule(Category.GAMING, "suffix", "riotgames.com"),
    Rule(Category.GAMING, "suffix", "leagueoflegends.com"),
    Rule(Category.GAMING, "suffix", "valorant.com"),
    Rule(Category.GAMING, "suffix", "blizzard.com"),
    Rule(Category.GAMING, "suffix", "battle.net"),
    Rule(Category.GAMING, "suffix", "activision.com"),
    Rule(Category.GAMING, "suffix", "ea.com"),
    Rule(Category.GAMING, "suffix", "origin.com"),
    Rule(Category.GAMING, "suffix", "ubisoft.com"),
    Rule(Category.GAMING, "suffix", "uplay.com"),
    Rule(Category.GAMING, "suffix", "roblox.com"),
    Rule(Category.GAMING, "suffix", "rbxcdn.com"),
    Rule(Category.GAMING, "suffix", "minecraft.net"),
    Rule(Category.GAMING, "suffix", "mojang.com"),
    Rule(Category.GAMING, "suffix", "xbox.com"),
    Rule(Category.GAMING, "suffix", "xboxlive.com"),
    Rule(Category.GAMING, "suffix", "playfab.com"),
    Rule(Category.GAMING, "suffix", "playstation.com"),
    Rule(Category.GAMING, "suffix", "psn.com"),
    Rule(Category.GAMING, "suffix", "nintendo.com"),
    Rule(Category.GAMING, "suffix", "gog.com"),
    Rule(Category.GAMING, "suffix", "itch.io"),
    Rule(Category.GAMING, "suffix", "gameloft.com"),
    Rule(Category.GAMING, "suffix", "supercell.com"),
    Rule(Category.GAMING, "suffix", "clashofclans.com"),
    Rule(Category.GAMING, "suffix", "pubg.com"),
    Rule(Category.GAMING, "suffix", "fortnite.com"),
    Rule(Category.GAMING, "suffix", "2game.com"),
    Rule(Category.GAMING, "suffix", "poki.com"),
    Rule(Category.GAMING, "contains", "gameserver"),
    Rule(Category.GAMING, "contains", "gamecenter"),

    # -----------------------------------------------------------------------
    # EDUCATION
    # -----------------------------------------------------------------------
    Rule(Category.EDUCATION, "suffix", "wikipedia.org"),
    Rule(Category.EDUCATION, "suffix", "wikimedia.org"),
    Rule(Category.EDUCATION, "suffix", "khanacademy.org"),
    Rule(Category.EDUCATION, "suffix", "coursera.org"),
    Rule(Category.EDUCATION, "suffix", "udemy.com"),
    Rule(Category.EDUCATION, "suffix", "edx.org"),
    Rule(Category.EDUCATION, "suffix", "duolingo.com"),
    Rule(Category.EDUCATION, "suffix", "quizlet.com"),
    Rule(Category.EDUCATION, "suffix", "britannica.com"),
    Rule(Category.EDUCATION, "suffix", "scholar.google.com"),
    Rule(Category.EDUCATION, "suffix", "academia.edu"),
    Rule(Category.EDUCATION, "suffix", "researchgate.net"),
    Rule(Category.EDUCATION, "suffix", "jstor.org"),
    Rule(Category.EDUCATION, "suffix", "ted.com"),
    Rule(Category.EDUCATION, "suffix", "ted.org"),
    Rule(Category.EDUCATION, "suffix", "skillshare.com"),
    Rule(Category.EDUCATION, "suffix", "lynda.com"),
    Rule(Category.EDUCATION, "suffix", "linkedin.com"),
    Rule(Category.EDUCATION, "suffix", "udacity.com"),
    Rule(Category.EDUCATION, "suffix", "codecademy.com"),
    Rule(Category.EDUCATION, "suffix", "freecodecamp.org"),
    Rule(Category.EDUCATION, "suffix", "w3schools.com"),
    Rule(Category.EDUCATION, "suffix", "stackoverflow.com"),
    Rule(Category.EDUCATION, "suffix", "mathway.com"),
    Rule(Category.EDUCATION, "suffix", "wolframalpha.com"),
    Rule(Category.EDUCATION, "suffix", "brainly.com"),
    Rule(Category.EDUCATION, "suffix", "quora.com"),
    Rule(Category.EDUCATION, "suffix", "chegg.com"),

    # -----------------------------------------------------------------------
    # TECH_INFRASTRUCTURE — connectivity / captive portal checks (must precede
    # PRODUCTIVITY to avoid gstatic.com suffix matching these)
    # -----------------------------------------------------------------------
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "connectivitycheck.gstatic.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "connectivitycheck.platform.hicloud.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "contains", "connectivitycheck"),

    # -----------------------------------------------------------------------
    # PRODUCTIVITY
    # -----------------------------------------------------------------------
    Rule(Category.PRODUCTIVITY, "suffix", "google.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "googleapis.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "gstatic.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "gmail.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "drive.google.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "docs.google.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "calendar.google.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "meet.google.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "microsoft.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "live.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "office.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "office365.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "microsoftonline.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "sharepoint.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "teams.microsoft.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "outlook.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "skype.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "zoom.us"),
    Rule(Category.PRODUCTIVITY, "suffix", "zoomgov.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "slack.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "notion.so"),
    Rule(Category.PRODUCTIVITY, "suffix", "notion.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "trello.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "asana.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "atlassian.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "jira.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "confluence.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "dropbox.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "box.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "icloud.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "me.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "evernote.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "todoist.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "github.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "gitlab.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "bitbucket.org"),
    Rule(Category.PRODUCTIVITY, "suffix", "1password.com"),
    Rule(Category.PRODUCTIVITY, "suffix", "lastpass.com"),

    # -----------------------------------------------------------------------
    # NEWS_MEDIA
    # -----------------------------------------------------------------------
    Rule(Category.NEWS_MEDIA, "suffix", "bbc.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "bbc.co.uk"),
    Rule(Category.NEWS_MEDIA, "suffix", "bbc.net"),
    Rule(Category.NEWS_MEDIA, "suffix", "cnn.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "foxnews.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "nytimes.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "theguardian.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "reuters.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "apnews.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "aljazeera.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "aljazeera.net"),
    Rule(Category.NEWS_MEDIA, "suffix", "washingtonpost.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "wsj.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "bloomberg.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "businessinsider.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "huffpost.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "vice.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "buzzfeed.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "techcrunch.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "theverge.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "wired.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "arstechnica.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "slashdot.org"),
    Rule(Category.NEWS_MEDIA, "suffix", "news.ycombinator.com"),
    Rule(Category.NEWS_MEDIA, "suffix", "medium.com"),

    # -----------------------------------------------------------------------
    # SHOPPING
    # -----------------------------------------------------------------------
    Rule(Category.SHOPPING, "suffix", "amazon.com"),
    Rule(Category.SHOPPING, "suffix", "amazon.co.uk"),
    Rule(Category.SHOPPING, "suffix", "amazon.de"),
    Rule(Category.SHOPPING, "suffix", "amazon.sa"),
    Rule(Category.SHOPPING, "suffix", "ssl-images-amazon.com"),
    Rule(Category.SHOPPING, "suffix", "media-amazon.com"),
    Rule(Category.SHOPPING, "suffix", "ebay.com"),
    Rule(Category.SHOPPING, "suffix", "ebayimg.com"),
    Rule(Category.SHOPPING, "suffix", "aliexpress.com"),
    Rule(Category.SHOPPING, "suffix", "alibaba.com"),
    Rule(Category.SHOPPING, "suffix", "taobao.com"),
    Rule(Category.SHOPPING, "suffix", "walmart.com"),
    Rule(Category.SHOPPING, "suffix", "target.com"),
    Rule(Category.SHOPPING, "suffix", "bestbuy.com"),
    Rule(Category.SHOPPING, "suffix", "etsy.com"),
    Rule(Category.SHOPPING, "suffix", "shopify.com"),
    Rule(Category.SHOPPING, "suffix", "myshopify.com"),
    Rule(Category.SHOPPING, "suffix", "booking.com"),
    Rule(Category.SHOPPING, "suffix", "airbnb.com"),
    Rule(Category.SHOPPING, "suffix", "airbnb-static.com"),
    Rule(Category.SHOPPING, "suffix", "expedia.com"),
    Rule(Category.SHOPPING, "suffix", "skyscanner.com"),
    Rule(Category.SHOPPING, "suffix", "kayak.com"),
    Rule(Category.SHOPPING, "suffix", "noon.com"),
    Rule(Category.SHOPPING, "suffix", "souq.com"),

    # -----------------------------------------------------------------------
    # TECH_INFRASTRUCTURE — catch-all for CDN / cloud / connectivity checks
    # -----------------------------------------------------------------------
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "akamaiedge.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "akamaitechnologies.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "akamai.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "cloudfront.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "fastly.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "cloudflare.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "cloudflare.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "edgecastcdn.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "awsstatic.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "amazonaws.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "azure.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "azure.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "azureedge.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "azurewebsites.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "windows.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "msecnd.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "visualstudio.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "vsts.me"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "google-analytics.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "connectivitycheck.gstatic.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "connectivitycheck.platform.hicloud.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "captive.apple.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "msftconnecttest.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "dns.msftncsi.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "contains", "connectivitycheck"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "ocsp.apple.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "ocsp.digicert.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "ocsp.comodoca.com"),
    # Tailscale MagicDNS: real domains rewritten under *.ts.net are still
    # whatever the underlying service is, but the rewrite itself is private
    # mesh infrastructure — never user-facing content. Keeps the AI from
    # misreading lookalike subdomains (e.g. web.whatsapp.com.<tail>.ts.net)
    # as phishing and firing false CRITICAL alerts.
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "ts.net"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "crl.microsoft.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "letsencrypt.org"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "time.apple.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "time.windows.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "huawei.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "hicloud.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "hms.hicloud.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "hwcld.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "update.googleapis.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "fonts.googleapis.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "fonts.gstatic.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "play.google.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "clients1.google.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "clients2.google.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "clients3.google.com"),
    Rule(Category.TECH_INFRASTRUCTURE, "suffix", "clients4.google.com"),
]
